"""Add users table

Revision ID: 20251217_add_users_table
Revises: 20251217_add_unique_file_hash
Create Date: 2025-12-17 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251217_add_users_table'
down_revision: Union[str, None] = '20251217_add_unique_file_hash'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###

    # 创建用户表
    op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键'),
        sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
        sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希'),
        sa.Column('role', sa.String(length=20), nullable=False, comment='角色: admin/manager'),
        sa.Column('store_id', sa.Integer(), nullable=True, comment='关联门店ID (管理员为NULL)'),
        sa.Column('full_name', sa.String(length=100), nullable=True, comment='真实姓名'),
        sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
        sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
        sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
        sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
        sa.Column('current_token', sa.String(length=500), nullable=True, comment='当前有效的token (用于单设备登录控制)'),
        sa.Column('token_expires_at', sa.DateTime(), nullable=True, comment='token过期时间'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='用户表'
    )

    # 创建索引
    op.create_index('idx_username', 'users', ['username'], unique=True)
    op.create_index('idx_role', 'users', ['role'], unique=False)
    op.create_index('idx_store_id', 'users', ['store_id'], unique=False)

    # 插入初始用户数据
    # 管理员用户 (可以访问所有门店)
    op.execute("""
        INSERT INTO users (username, hashed_password, role, store_id, full_name, email, phone, is_active)
        VALUES (
            'admin',
            '$pbkdf2-sha256$29000$.n8PgXDufa91zjlnbE3J.Q$P5vIMVWWgkxXfwVBC4vuSC2MTDk49w0ntDTlF8oMhso',
            'admin',
            NULL,
            '系统管理员',
            'admin@ktv.com',
            '13800138000',
            TRUE
        )
    """)

    # 店长用户 (只能访问门店1)
    op.execute("""
        INSERT INTO users (username, hashed_password, role, store_id, full_name, email, phone, is_active)
        VALUES (
            'manager',
            '$pbkdf2-sha256$29000$wxjjPAegtBYiZExpjRFibA$XXxQ9BL4LBGC0Hp7FOsmgVdTUYyksQEdsHRIlqGoeOU',
            'manager',
            1,
            '门店店长',
            'manager@ktv.com',
            '13800138001',
            TRUE
        )
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移"""
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除用户表
    op.drop_index('idx_store_id', table_name='users')
    op.drop_index('idx_role', table_name='users')
    op.drop_index('idx_username')
    op.drop_table('users')

    # ### end Alembic commands ###
