"""Initial tables

Revision ID: 628a6c05dd81
Revises: 
Create Date: 2025-12-10 21:50:12.150742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '628a6c05dd81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='代理键'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='关联门店'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='员工姓名'),
    sa.Column('department', sa.String(length=50), nullable=True, comment='部门'),
    sa.Column('position', sa.String(length=50), nullable=True, comment='职位'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否在职'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='员工维度表'
    )
    op.create_index('idx_store_name', 'dim_employee', ['store_id', 'name'], unique=False)
    op.create_index(op.f('ix_dim_employee_store_id'), 'dim_employee', ['store_id'], unique=False)
    op.create_table('dim_payment_method',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='代理键'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='支付方式代码'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='支付方式名称'),
    sa.Column('category', sa.String(length=20), nullable=False, comment='分类: income/equity/cost'),
    sa.Column('is_core', sa.Boolean(), nullable=True, comment='是否核心字段(独立建列)'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序顺序'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='支付方式维度表'
    )
    op.create_index('idx_category', 'dim_payment_method', ['category'], unique=False)
    op.create_index('idx_code', 'dim_payment_method', ['code'], unique=True)
    op.create_table('dim_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='代理键'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='关联门店'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='商品名称'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='商品分类'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='单位'),
    sa.Column('price', sa.Integer(), nullable=True, comment='单价(分)'),
    sa.Column('cost', sa.Integer(), nullable=True, comment='成本(分)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否在售'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='商品维度表'
    )
    op.create_index('idx_category', 'dim_product', ['category'], unique=False)
    op.create_index('idx_store_product', 'dim_product', ['store_id', 'name'], unique=False)
    op.create_index(op.f('ix_dim_product_store_id'), 'dim_product', ['store_id'], unique=False)
    op.create_table('dim_room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='代理键'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='关联门店'),
    sa.Column('room_no', sa.String(length=50), nullable=False, comment='包厢号'),
    sa.Column('room_name', sa.String(length=50), nullable=True, comment='包厢名称'),
    sa.Column('room_type', sa.String(length=50), nullable=True, comment='包厢类型'),
    sa.Column('area_name', sa.String(length=50), nullable=True, comment='区域名称'),
    sa.Column('capacity', sa.Integer(), nullable=True, comment='容纳人数'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='包厢维度表'
    )
    op.create_index('idx_room_type', 'dim_room', ['room_type'], unique=False)
    op.create_index('idx_store_room', 'dim_room', ['store_id', 'room_no'], unique=True)
    op.create_index(op.f('ix_dim_room_store_id'), 'dim_room', ['store_id'], unique=False)
    op.create_table('dim_store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='代理键'),
    sa.Column('store_code', sa.String(length=20), nullable=True, comment='门店编码'),
    sa.Column('store_name', sa.String(length=100), nullable=False, comment='门店名(标准化)'),
    sa.Column('original_name', sa.String(length=100), nullable=True, comment='原始门店名(用于匹配)'),
    sa.Column('region', sa.String(length=50), nullable=True, comment='所属区域/城市'),
    sa.Column('address', sa.String(length=200), nullable=True, comment='门店地址'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_code'),
    comment='门店维度表'
    )
    op.create_index('idx_store_code', 'dim_store', ['store_code'], unique=False)
    op.create_index('idx_store_name', 'dim_store', ['store_name'], unique=True)
    op.create_table('fact_booking',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键'),
    sa.Column('batch_id', sa.BigInteger(), nullable=False, comment='关联批次'),
    sa.Column('biz_date', sa.Date(), nullable=False, comment='营业日期'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='关联门店'),
    sa.Column('employee_id', sa.Integer(), nullable=True, comment='关联员工(订位人)'),
    sa.Column('department', sa.String(length=50), nullable=True, comment='部门(冗余)'),
    sa.Column('customer_name', sa.String(length=50), nullable=True, comment='订位人/客户名'),
    sa.Column('booking_qty', sa.Integer(), nullable=True, comment='订台数'),
    sa.Column('sales_amount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='销售金额(应收)'),
    sa.Column('actual_amount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='实收金额'),
    sa.Column('base_performance', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='基本业绩'),
    sa.Column('service_fee', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='服务费'),
    sa.Column('auto_deduction', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='自动扣减'),
    sa.Column('gift_amount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='赠送金额'),
    sa.Column('discount_amount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='折扣金额'),
    sa.Column('free_amount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='免单金额'),
    sa.Column('credit_amount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='挂账金额'),
    sa.Column('round_off_amount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='抹零金额'),
    sa.Column('adjustment_amount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='调整金额'),
    sa.Column('pay_wechat', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='微信支付'),
    sa.Column('pay_alipay', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='支付宝'),
    sa.Column('pay_cash', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='现金'),
    sa.Column('pay_pos', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='POS/银行卡'),
    sa.Column('pay_member', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='会员支付'),
    sa.Column('pay_douyin', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='抖音'),
    sa.Column('pay_meituan', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='美团/团购'),
    sa.Column('extra_payments', sa.JSON(), nullable=True, comment='其他支付方式(JSON)'),
    sa.Column('extra_info', sa.JSON(), nullable=True, comment='其他扩展信息(JSON)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='入库时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='预订汇总事实表'
    )
    op.create_index('idx_batch', 'fact_booking', ['batch_id'], unique=False)
    op.create_index('idx_date_store', 'fact_booking', ['biz_date', 'store_id'], unique=False)
    op.create_index('idx_date_store_employee', 'fact_booking', ['biz_date', 'store_id', 'employee_id'], unique=False)
    op.create_index('idx_employee', 'fact_booking', ['employee_id'], unique=False)
    op.create_index(op.f('ix_fact_booking_batch_id'), 'fact_booking', ['batch_id'], unique=False)
    op.create_table('fact_room',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键'),
    sa.Column('batch_id', sa.BigInteger(), nullable=False, comment='关联批次'),
    sa.Column('biz_date', sa.Date(), nullable=False, comment='营业日期'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='关联门店'),
    sa.Column('room_id', sa.Integer(), nullable=True, comment='关联包厢'),
    sa.Column('order_no', sa.String(length=50), nullable=False, comment='开台单号(业务主键)'),
    sa.Column('billing_mode', sa.String(length=100), nullable=True, comment='开房计费模式'),
    sa.Column('open_time', sa.DateTime(), nullable=True, comment='开房时间'),
    sa.Column('close_time', sa.DateTime(), nullable=True, comment='关房时间'),
    sa.Column('clean_time', sa.DateTime(), nullable=True, comment='清洁时间'),
    sa.Column('duration_min', sa.Integer(), nullable=True, comment='时长(分钟)'),
    sa.Column('time_slot', sa.String(length=20), nullable=True, comment='时段'),
    sa.Column('booker', sa.String(length=50), nullable=True, comment='订房人'),
    sa.Column('booker_dept', sa.String(length=50), nullable=True, comment='订房人部门'),
    sa.Column('sales_manager', sa.String(length=50), nullable=True, comment='销售经理'),
    sa.Column('bill_total', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='账单合计'),
    sa.Column('receivable_amount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='应收金额'),
    sa.Column('actual_amount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='实收金额'),
    sa.Column('base_performance', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='基本业绩'),
    sa.Column('min_consumption', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='低消费'),
    sa.Column('min_consumption_diff', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='低消差额'),
    sa.Column('gift_amount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='赠送金额'),
    sa.Column('room_discount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='房费折扣'),
    sa.Column('beverage_discount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='酒水折扣'),
    sa.Column('free_amount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='免单金额'),
    sa.Column('credit_amount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='挂账金额'),
    sa.Column('round_off_amount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='抹零金额'),
    sa.Column('adjustment_amount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='调整金额'),
    sa.Column('pay_wechat', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='微信支付'),
    sa.Column('pay_alipay', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='支付宝'),
    sa.Column('pay_cash', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='现金'),
    sa.Column('pay_pos', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='POS/银行卡'),
    sa.Column('pay_member', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='会员支付'),
    sa.Column('pay_douyin', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='抖音'),
    sa.Column('pay_meituan', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='美团/团购'),
    sa.Column('extra_payments', sa.JSON(), nullable=True, comment='其他支付方式(JSON)'),
    sa.Column('extra_info', sa.JSON(), nullable=True, comment='其他扩展信息(JSON)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='入库时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='包厢开台事实表'
    )
    op.create_index('idx_batch', 'fact_room', ['batch_id'], unique=False)
    op.create_index('idx_date_store', 'fact_room', ['biz_date', 'store_id'], unique=False)
    op.create_index('idx_date_store_room', 'fact_room', ['biz_date', 'store_id', 'room_id'], unique=False)
    op.create_index('idx_order_no', 'fact_room', ['order_no'], unique=True)
    op.create_index('idx_room', 'fact_room', ['room_id'], unique=False)
    op.create_index(op.f('ix_fact_room_batch_id'), 'fact_room', ['batch_id'], unique=False)
    op.create_table('fact_sales',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键'),
    sa.Column('batch_id', sa.BigInteger(), nullable=False, comment='关联批次'),
    sa.Column('biz_date', sa.Date(), nullable=False, comment='营业日期'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='关联门店'),
    sa.Column('product_id', sa.Integer(), nullable=True, comment='关联商品'),
    sa.Column('product_name', sa.String(length=100), nullable=True, comment='商品名称'),
    sa.Column('category_name', sa.String(length=50), nullable=True, comment='类别名称'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='单位'),
    sa.Column('area', sa.String(length=50), nullable=True, comment='区域'),
    sa.Column('sales_qty', sa.Integer(), nullable=True, comment='销售数量'),
    sa.Column('sales_amount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='销售金额'),
    sa.Column('sales_qty_pure', sa.Integer(), nullable=True, comment='纯销售数量'),
    sa.Column('sales_qty_package', sa.Integer(), nullable=True, comment='套餐子物品数量'),
    sa.Column('sales_qty_example', sa.Integer(), nullable=True, comment='例送子物品数量'),
    sa.Column('sales_amount_pure', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='纯销售金额'),
    sa.Column('sales_amount_package', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='套餐子物品金额'),
    sa.Column('gift_qty', sa.Integer(), nullable=True, comment='赠送数量'),
    sa.Column('gift_amount', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='赠送金额'),
    sa.Column('gift_qty_pure', sa.Integer(), nullable=True, comment='纯赠送数量'),
    sa.Column('gift_qty_package', sa.Integer(), nullable=True, comment='套餐赠送数量'),
    sa.Column('cost_total', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='成本小计'),
    sa.Column('cost_sales', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='销售成本'),
    sa.Column('cost_gift', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='赠送成本'),
    sa.Column('profit', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='毛利'),
    sa.Column('profit_rate', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='毛利率(%)'),
    sa.Column('extra_info', sa.JSON(), nullable=True, comment='其他扩展信息(JSON)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='入库时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='酒水销售事实表'
    )
    op.create_index('idx_batch', 'fact_sales', ['batch_id'], unique=False)
    op.create_index('idx_category', 'fact_sales', ['category_name'], unique=False)
    op.create_index('idx_date_store', 'fact_sales', ['biz_date', 'store_id'], unique=False)
    op.create_index('idx_date_store_product', 'fact_sales', ['biz_date', 'store_id', 'product_id'], unique=False)
    op.create_index('idx_product', 'fact_sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_fact_sales_batch_id'), 'fact_sales', ['batch_id'], unique=False)
    op.create_table('meta_file_batch',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键'),
    sa.Column('batch_no', sa.String(length=50), nullable=False, comment='唯一批次号 (YYYYMMDD_Store_Type)'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='文件存储路径'),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='文件MD5哈希(防重复)'),
    sa.Column('store_id', sa.Integer(), nullable=False, comment='关联门店ID'),
    sa.Column('table_type', sa.String(length=50), nullable=False, comment='表类型: booking/room/sales'),
    sa.Column('data_start_date', sa.DateTime(), nullable=True, comment='数据开始日期'),
    sa.Column('data_end_date', sa.DateTime(), nullable=True, comment='数据结束日期'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: pending/processing/success/failed'),
    sa.Column('row_count', sa.Integer(), nullable=True, comment='导入行数'),
    sa.Column('error_count', sa.Integer(), nullable=True, comment='错误行数'),
    sa.Column('error_log', sa.Text(), nullable=True, comment='错误日志(JSON格式)'),
    sa.Column('upload_user', sa.String(length=50), nullable=True, comment='上传人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_no'),
    comment='文件导入批次管理表'
    )
    op.create_index('idx_batch_no', 'meta_file_batch', ['batch_no'], unique=True)
    op.create_index('idx_file_hash', 'meta_file_batch', ['file_hash'], unique=False)
    op.create_index('idx_status', 'meta_file_batch', ['status'], unique=False)
    op.create_index('idx_store_date', 'meta_file_batch', ['store_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_meta_file_batch_store_id'), 'meta_file_batch', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_file_batch_store_id'), table_name='meta_file_batch')
    op.drop_index('idx_store_date', table_name='meta_file_batch')
    op.drop_index('idx_status', table_name='meta_file_batch')
    op.drop_index('idx_file_hash', table_name='meta_file_batch')
    op.drop_index('idx_batch_no', table_name='meta_file_batch')
    op.drop_table('meta_file_batch')
    op.drop_index(op.f('ix_fact_sales_batch_id'), table_name='fact_sales')
    op.drop_index('idx_product', table_name='fact_sales')
    op.drop_index('idx_date_store_product', table_name='fact_sales')
    op.drop_index('idx_date_store', table_name='fact_sales')
    op.drop_index('idx_category', table_name='fact_sales')
    op.drop_index('idx_batch', table_name='fact_sales')
    op.drop_table('fact_sales')
    op.drop_index(op.f('ix_fact_room_batch_id'), table_name='fact_room')
    op.drop_index('idx_room', table_name='fact_room')
    op.drop_index('idx_order_no', table_name='fact_room')
    op.drop_index('idx_date_store_room', table_name='fact_room')
    op.drop_index('idx_date_store', table_name='fact_room')
    op.drop_index('idx_batch', table_name='fact_room')
    op.drop_table('fact_room')
    op.drop_index(op.f('ix_fact_booking_batch_id'), table_name='fact_booking')
    op.drop_index('idx_employee', table_name='fact_booking')
    op.drop_index('idx_date_store_employee', table_name='fact_booking')
    op.drop_index('idx_date_store', table_name='fact_booking')
    op.drop_index('idx_batch', table_name='fact_booking')
    op.drop_table('fact_booking')
    op.drop_index('idx_store_name', table_name='dim_store')
    op.drop_index('idx_store_code', table_name='dim_store')
    op.drop_table('dim_store')
    op.drop_index(op.f('ix_dim_room_store_id'), table_name='dim_room')
    op.drop_index('idx_store_room', table_name='dim_room')
    op.drop_index('idx_room_type', table_name='dim_room')
    op.drop_table('dim_room')
    op.drop_index(op.f('ix_dim_product_store_id'), table_name='dim_product')
    op.drop_index('idx_store_product', table_name='dim_product')
    op.drop_index('idx_category', table_name='dim_product')
    op.drop_table('dim_product')
    op.drop_index('idx_code', table_name='dim_payment_method')
    op.drop_index('idx_category', table_name='dim_payment_method')
    op.drop_table('dim_payment_method')
    op.drop_index(op.f('ix_dim_employee_store_id'), table_name='dim_employee')
    op.drop_index('idx_store_name', table_name='dim_employee')
    op.drop_table('dim_employee')
    # ### end Alembic commands ###

